### ISSUE TITLE
Slang watch recursive

### ISSUE THREAD

**Issue by Roboroads** [Tienisto/slang#118]
**Motivation**
Because the langfiles can become quite the list I group modules in their own directory. Slang watch does not trigger on the files in thje directories.

```text
assets/i18n
├── alerts
│   ├── alerts.i18n.yaml
│   └── alerts_nl.i18n.yaml
├── bottomBarPage
│   ├── bottomBarPage.i18n.yaml
│   └── bottomBarPage_nl.i18n.yaml
├── errors
│   ├── errors.i18n.yaml
│   └── errors_nl.i18n.yaml
├── login
│   ├── login.i18n.yaml
│   └── login_nl.i18n.yaml
└── maintenancePage
    ├── maintenancePage.i18n.yaml
    └── maintenancePage_nl.i18n.yaml
```

**Developer Experience**
Adding a -r / --recursive option to the arguments of watch would be nice.

**Comment by noga-dev** [comment]
You mean watch works for you if you place all the files together?

In this issue watch doesn't seem to work at all https://github.com/Tienisto/slang/issues/90

**Comment by Tienisto** [comment]
He is refering to the custom command `flutter pub run slang watch` I guess. (See https://github.com/Tienisto/slang#-auto-rebuild)

In general, you should use `flutter pub run slang` during development because it is much faster than `build_runner`. You may use `build_runner` initially to generate everything at once but changing i18n files incrementally is kind of unstable using `build_runner`.

**Comment by Roboroads** [comment]
> He is refering to the custom command `flutter pub run slang watch` I guess.

This, yes.

**Comment by Tienisto** [comment]
`flutter pub run slang watch` now works recursively in `v3.6.0`.
