### ISSUE TITLE
Only apply changed strings in `_missing_translations.json`

### ISSUE THREAD

**Issue by adil192** [Tienisto/slang#129]
**Motivation**
When I'm applying translations, there is usually only one language that's changed at a time. I therefore need to type in
```bash
flutter pub run slang apply --locale=zh-Hant-TW
```
which is quite tedious especially with the longer locale codes.

**Developer Experience**
I propose a new flag, e.g.
```bash
flutter pub run slang apply --only-changed
```
which would only apply translations from locales that have changed from the default translation file.

***

e.g.
```json
{
  "@@info": [
    "Here are translations that exist in <en> but not in secondary locales.",
    "After editing this file, you can run 'flutter pub run slang apply --locale=<locale>' to quickly apply the newly added translations."
  ],
  "cs": {
    "eg": "This is the (unchanged) English translation."
  },
  "de": {
    "eg": "This is the (changed) German translation."
  }
}
```
Running `flutter pub run slang apply --only-changed` on the above would be equivalent to
```bash
flutter pub run slang apply --locale=de
```

**Comment by Tienisto** [comment]
Thanks for noticing this UX issue!

I think that applying unchanged translations is never useful. So instead of adding a flag, `flutter pub run slang apply` will only apply changed locales by default. The developer can still use `--locale=` to apply a specific locale where it might be the same (`en-US`, `en-GB`).

Changed in `v3.14.0`
